# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f27de1721ecb6dadf608f73b7ff7a5b175f648570bac5ad358fd75a2e55383ab3ca7848d538019485d603440843a484f1a0249be4b8be2bf55d00dab8609e2c

test:
  secret_key_base: 1fb6761bf64370989f30be39c299ffce47e24a89b37504494af8a2d8aa4549e14844a8e80b721e9a2ad0f22fafba5d73daab9d1c32d5d48e126352e0433ecc99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
