Contact.create(name:'Pepito', adress:'Avd del Escalofreido')
Contact.create(name:'Margarito', adress:'Avd del sadgag')
Contact.create(name:'Manolito', adress:'Calle Desengaño 21')
Contact.create(name:'Paquito', adress:'Plaza de la Virgen(que no es vírgen ya)')

Phone.create(contact_id: 1, phone_number: 982223354, description: "Su casa")
Phone.create(contact_id: 1, phone_number: 665778899, description: "Móvil")
Phone.create(contact_id: 1, phone_number: 982223123, description: "Su mamá")
Phone.create(contact_id: 2, phone_number: 984458899, description: "Casa")
Phone.create(contact_id: 3, phone_number: 669554477, description: "Móvil")
Phone.create(contact_id: 3, phone_number: 982223112, description: "Su casa")
Phone.create(contact_id: 4, phone_number: 986696969, description: "Amante")
Phone.create(contact_id: 4, phone_number: 982221176, description: "Su casa")
Phone.create(contact_id: 4, phone_number: 962225544, description: "Tutor proyecto hombre")

Email.create(contact_id: 1, email_adress: 'pepitopepón@gmail.com', description: 'Personal')
Email.create(contact_id: 1, email_adress: 'nenikahXulah_69.com', description: 'Ocio')
Email.create(contact_id: 2, email_adress: 'margarito1122@company8.com', description: 'Trabajo')
Email.create(contact_id: 2, email_adress: 'margP@gmail.com', description: 'Personal')
Email.create(contact_id: 3, email_adress: 'manolitoito@gmail.com', description: 'Personal')
Email.create(contact_id: 4, email_adress: 'paquitoperez@gmail.com', description: 'Personal')
Email.create(contact_id: 4, email_adress: 'pakitoXuloh_69@gmail.com', description: 'Trabajo')